### PR TITLE
Updates for Foundation 4

### PR DESCRIPTION
**Pull request by andrewmartin**
This update now loads in the latest Foundation 4 gem.  I updated the application javascript manifest, loading in edge gems for middleman related gems, and dropped in sample content into the index view from Foundation 4. May want to review `$(document).ready ->` call in the `app.js.coffee` file.

### CODE REVIEW

**Comment by Linuus** [comment]
Why do we need to include all js files? Aren't those included in the gem like the stylesheets?

**Comment by andrewmartin** [comment]
Good point. I think the manifest should at least include references to the gem versions of the JS files though. My bad. 
—
Andrew Martin
www.andrewmart.in

**Comment by Linuus** [comment]
I couldn't make it work without including the js files though... Otherwise I just got Sprocket FileNotFound when doing something like:
//= require foundation

**Comment by andrewmartin** [comment]
The gem might not work with sprockets. That's strange though. I would suggest trying a different path; I know the @import statements work great in the CSS manifest. 
—
Andrew Martin
www.andrewmart.in

**Comment by tenpn** [comment]
what's the status of this? is f4 usable if I pulled directly from your branch, @andrewmartin?

**Comment by andrewmartin** [comment]
@tenpn Yep, it should work. I think there may be some easily fixed errors with the JS...feel free to submit a pull request if you get those cleaned. The CSS is set up real nice though.

**Comment by tenpn** [comment]
a pull request to the pull request...? #ossinception

**Comment by andrewmartin** [comment]
Hahaha. Yeah. I guess?

**Comment by tenpn** [comment]
I played around with it last night, and did encounter some javascript problems. Unfortunately I'm almost a complete noob to proper web development, so I post the details here if anyone has the time:

Here's the webpage with the problem:
http://testing.tenpn.com/
When you hover over the "Pluings" item in the foundation top-bar control, you should get a drop-down. You don't.

My top-bar control implementation is here (look for `/ top bar menu`):
https://github.com/tenpn/tenpndotcom/blob/master/source/layouts/layout.haml
It is translated from a working html example to haml, but I see no typos. Here's a gist containing the working html:
https://gist.github.com/tenpn/4506daa14b5f2af346b3

**Pull request merged**
